pipeline {
    agent any
    stages{
	   stage('Clone the Repo'){
          steps{
               echo "Code cloning in progress"
               git branch: 'main', url: 'https://github.com/send2durai/windows_automation.git'
            }
        }
    stage("Are we good to deploy? Say yes or no?"){
        input{
           message "Should we start the Job?"
             }
	    steps{
	      echo 'India is my country!'
	    }
	}
    stage('Build') {
        steps {
            echo 'Building..'
			sh '''
			   cd python_automation
			   python --version
			   sudo sh uppercase.py
			   '''
            }
    }
    stage('Test'){
        steps {
            echo 'Testing..'
            }
    }
    stage('Deploy') {
        steps {
            echo 'Deploying....'
            }
    }
	stage('Workspace CleanUp'){
		steps{
			sh '''
			    echo "Cleaning the Jenkins workspace"
			   '''
			cleanWs()
            }
		}
	}
}
